In [ ]:
ARRAY PTTHON

In [ ]:
import array as arr
Eg_array = arr.array('i', [1, 2, 3, 4, 5])

print(Eg_array[0])
print(Eg_array[2])
print(Eg_array[3])

Eg_array[1] = 10
print(Eg_array)



1
3
4
array('i', [1, 10, 3, 4, 5])


In [ ]:
Eg_array.append(6)
print(Eg_array)

In [ ]:
Eg_array.extend([7, 8, 9])
print(Eg_array)

In [ ]:
Eg_array.remove(10)
print(Eg_array)

In [ ]:
Eg_array.pop()
print(Eg_array)

In [ ]:
# types of code
#Arrays:
import array as arr
arr = arr.array('B', [1,25,3, 4, 5,41,5])
print(arr)


array('B', [1, 25, 3, 4, 5, 41, 5])


In [ ]:
import array as arr
arr = arr.array('h', [-32746,-125,3, 4, 5,41,5,32127])
print(arr)

array('h', [-32746, -125, 3, 4, 5, 41, 5, 32127])


In [ ]:
#1. append()
#Adds an element to the end of the array.
import array as arr
arr = arr.array('i', [11, 22, 33, 44, 55,66,26,65])
print(arr)
arr.append(78)
print(arr)


array('i', [11, 22, 33, 44, 55, 66, 26, 65])
array('i', [11, 22, 33, 44, 55, 66, 26, 65, 78])


In [ ]:
#2. extend()
#Adds elements from an iterable (e.g., list) to the end of the array.
import array as arr
arr = arr.array('i', [1, 2, 3, 4, 5,6,26,5])
print(arr)

arr.extend([12,14,14])
print(arr)

array('i', [1, 2, 3, 4, 5, 6, 26, 5])
array('i', [1, 2, 3, 4, 5, 6, 26, 5, 12, 14, 14])


In [ ]:
#3. insert()
#Inserts an element at a specified position in the array.
import array as arr
arr = arr.array('i', [1, 2, 3, 4, 5,6,26,5])
print(arr)
arr.insert(4,24)
print(arr)
arr.insert(0,0)
print(arr)

array('i', [1, 2, 3, 4, 5, 6, 26, 5])
array('i', [1, 2, 3, 4, 24, 5, 6, 26, 5])
array('i', [0, 1, 2, 3, 4, 24, 5, 6, 26, 5])


In [ ]:
#4. pop()
#Removes and returns the last element, or the element at a specified position.
import array as arr
arr = arr.array('i', [1, 2, 3, 4, 5,6,26,5])
print(arr)
arr.pop()
print(arr)
arr.pop(2)
print(arr)


array('i', [1, 2, 3, 4, 5, 6, 26, 5])
array('i', [1, 2, 3, 4, 5, 6, 26])
array('i', [1, 2, 4, 5, 6, 26])


In [ ]:
#5. remove()
#Removes the first occurrence of a specified element
import array as arr
arr = arr.array('i', [1, 2, 3, 4, 5,6,26,5])
print(arr)
arr.remove(5)
print(arr)

array('i', [1, 2, 3, 4, 5, 6, 26, 5])
array('i', [1, 2, 3, 4, 6, 26, 5])


In [ ]:
#6. index()
#Returns the index of the first occurrence of a specified element.
import array as arr
arr = arr.array('i', [1, 2, 3, 4, 5,6,26,5])
print(arr)
print(arr.index(5))

array('i', [1, 2, 3, 4, 5, 6, 26, 5])
4


In [ ]:
#7. count()
#Returns the number of occurrences of a specified element.
import array as arr

# Creating an array of integers
arr = arr.array('i', [1, 2, 3, 4, 5, 6, 26, 5,4,4,4])
print("Original array:", arr)

print(arr.count(5))

Original array: array('i', [1, 2, 3, 4, 5, 6, 26, 5, 4, 4, 4])
2


In [ ]:
#8. reverse()
#Reverses the order of elements in the array.

import array as arr

# Creating an array of integers
arr = arr.array('i', [1, 2, 3, 4, 5, 6, 26, 5])
print("Original array:", arr)
arr.reverse()
print("Reversed Array: ",arr)
print(arr.reverse())

Original array: array('i', [1, 2, 3, 4, 5, 6, 26, 5])
Reversed Array:  array('i', [5, 26, 6, 5, 4, 3, 2, 1])
None


In [ ]:
#9. buffer_info()
#Returns a tuple containing the memory address and the number of elements in the array.
import array as arr

# Creating an array of integers
arr = arr.array('i', [1, 2, 3, 4, 5, 6, 26, 5])
print("Original array:", arr)

print(arr.buffer_info())

Original array: array('i', [1, 2, 3, 4, 5, 6, 26, 5])
(136667109107760, 8)


In [ ]:
#10. tolist()
#Converts the array to a regular list.
import array as arr

# Creating an array of integers
arr = arr.array('i', [1, 2, 3, 4, 5, 6, 26, 5])
print("Original array:", arr)
print(arr.tolist())

Original array: array('i', [1, 2, 3, 4, 5, 6, 26, 5])
[1, 2, 3, 4, 5, 6, 26, 5]


In [ ]:
#types of array
#1D Array
import numpy as np
a=np.array([1,2,3])
print(a)


[1 2 3]


In [ ]:
#2D Array
a =np.array([[2,4,6],[4,5,6],[6,5,7]])

print(a)
print(type(a))
a.ndim

[[2 4 6]
 [4 5 6]
 [6 5 7]]
<class 'numpy.ndarray'>


2

In [ ]:
#3d array

x= np.array([[[1,2,3], [4,5,6],[5,6,7]], [[4,5,6],[8,8,7],[8,9,7]]])
print(x)

print(type(x))
x.ndim

[[[1 2 3]
  [4 5 6]
  [5 6 7]]

 [[4 5 6]
  [8 8 7]
  [8 9 7]]]
<class 'numpy.ndarray'>


3

In [ ]:
import numpy as np
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
import numpy as np
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
import numpy as np

#full array with -6 values
np.full((4,4),0)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
np.arange(0,101,10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
import numpy as np
data = np.array([[5, 4, 0, 1],
                  [11, 4, 10, 7],
                  [7, 10, 5, 6],
                  [7, 12, 10, 4],
                  [3, 7, 3, 4]])

print(data)

[[ 5  4  0  1]
 [11  4 10  7]
 [ 7 10  5  6]
 [ 7 12 10  4]
 [ 3  7  3  4]]


In [ ]:
dt =[1,3,4]
sum(dt)

8

In [ ]:
data.max()

np.int64(12)

In [ ]:
data.mean()

np.float64(6.0)

In [ ]:
data.sum()

np.int64(120)

In [ ]:
np.full((4,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [ ]:
a=np.array([[2,4,6],[5,6,7],[8,10,12]])
print(a)
print(a.shape)

[[ 2  4  6]
 [ 5  6  7]
 [ 8 10 12]]
(3, 3)


In [ ]:
a=np.array([[2,4,6,4],[5,6,7,8],[8,10,12,4]]) #3,4 =12
print("Original Array:\n", a)
a.shape=(6,2)
print("Changed Array:\n",a)


Original Array:
 [[ 2  4  6  4]
 [ 5  6  7  8]
 [ 8 10 12  4]]
Changed Array:
 [[ 2  4]
 [ 6  4]
 [ 5  6]
 [ 7  8]
 [ 8 10]
 [12  4]]


In [ ]:
a.shape=(4,3)
print("Changed Array:\n",a)

Changed Array:
 [[ 2  4  6]
 [ 4  5  6]
 [ 7  8  8]
 [10 12  4]]


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[5,8,9]])
print(a.size)
print(a.shape)
print(a.ndim)
print(a.dtype)

9
(3, 3)
2
int64


In [ ]:
import numpy as np

x=np.random.randint(0,20,(6,5))
print(x)

[[10 19  0 13  4]
 [13 15  0 12  9]
 [ 5  1 18  9  2]
 [ 1 19 11  4  0]
 [ 3  2 16 14 10]
 [ 2  9 14  1  9]]


In [ ]:
x.shape

(6, 5)

In [ ]:
x.ravel()    # flatten arrey first to reshape

array([10, 19,  0, 13,  4, 13, 15,  0, 12,  9,  5,  1, 18,  9,  2,  1, 19,
       11,  4,  0,  3,  2, 16, 14, 10,  2,  9, 14,  1,  9])

In [ ]:
y=x.ravel()

In [ ]:
x.reshape(3,10)

array([[10, 19,  0, 13,  4, 13, 15,  0, 12,  9],
       [ 5,  1, 18,  9,  2,  1, 19, 11,  4,  0],
       [ 3,  2, 16, 14, 10,  2,  9, 14,  1,  9]])

In [ ]:
a1=np.array([[2,3],[5,6]])
print(a1)

a2=np.array([[4,5],[7,8]])
print(a2)

[[2 3]
 [5 6]]
[[4 5]
 [7 8]]


In [ ]:
np.vstack([a1,a2])

array([[2, 3],
       [5, 6],
       [4, 5],
       [7, 8]])

In [ ]:
np.hstack([a1,a2])

array([[2, 3, 4, 5],
       [5, 6, 7, 8]])

In [ ]:
np.concatenate([a1,a2],axis=0)

array([[2, 3],
       [5, 6],
       [4, 5],
       [7, 8]])

In [ ]:
np.concatenate([a1,a2],axis=1)

array([[2, 3, 4, 5],
       [5, 6, 7, 8]])

In [ ]:
# numpy array mathmatics

# addtion
array1=np.array([[1,2,3],
                 [4,5,6]])
array2=np.array([[7,8,9],
                 [10,11,12]])
array3=np.array([[8,6,9],
                 [10,23,11]])

sum_array=array1 + array2 + array3
print('addition:\n',sum_array)
sum_array.ndim

addition:
 [[16 16 21]
 [24 39 29]]


2

In [ ]:
import numpy as np
# substraction
np.subtract(20,10)

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6,])
c=np.array([1,3,4])
sub = a-b-c
print(sub)

[-4 -6 -7]


In [ ]:
import numpy as np
a=np.array([[1,2],[6,8]])
b=np.array([5,4])

result=a + b
print("result of a+b with brodcasting:\n",result)

result of a+b with brodcasting:
 [[ 6  6]
 [11 12]]


In [ ]:
# multiplication

import numpy as np
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

product_array = array1 * array2
print("Multiplication:\n", product_array)

Multiplication:
 [[ 7 16 27]
 [40 55 72]]


In [ ]:
#divition
import numpy as np
array1 = np.array([[10, 20, 30],
                   [40, 50, 60]])

array2 = np.array([[3, 4, 5],
                   [10, 5, 3]])

division_array = array1 / array2
print("Division:\n", division_array)
print(division_array.dtype)

Division:
 [[ 3.33333333  5.          6.        ]
 [ 4.         10.         20.        ]]
float64


In [ ]:
import numpy as np
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([7, 8, 9])

product_array = array1 * array2
print("Multiplication:\n", product_array)

Multiplication:
 [[ 7 16 27]
 [28 40 54]]


In [ ]:
# matrix multiplication
#no of column in first array must eqal to no of rows in econd array

x1=np.random.randint(0,10,(2,2))
x2=np.random.randint(0,10,(2,2))


In [ ]:
x1

array([[0, 6],
       [5, 7]])

In [ ]:
x2

array([[6, 2],
       [8, 0]])

In [ ]:
np.dot(x1,x2)

array([[48,  0],
       [86, 10]])

In [ ]:
# string functions
import numpy as np
x=np.array([1,2,3,'name'])
x

array(['1', '2', '3', 'name'], dtype='<U21')

In [ ]:
np.char.capitalize(x)

array(['1', '2', '3', 'Name'], dtype='<U21')

In [ ]:
np.char.center(x,10,fillchar='*')

array(['****1*****', '****2*****', '****3*****', '***name***'],
      dtype='<U10')

In [ ]:
x=np.array([1,2,3,'data engineering'])
x

array(['1', '2', '3', 'data engineering'], dtype='<U21')

In [ ]:
print(np.char.upper(x))
print(np.char.lower(x))
print(np.char.title(x))

['1' '2' '3' 'DATA ENGINEERING']
['1' '2' '3' 'data engineering']
['1' '2' '3' 'Data Engineering']


In [ ]:
y=np.array(["Data Science","Machine Learning"])
np.char.split(y,sep='a')

array([list(['D', 't', ' Science']), list(['M', 'chine Le', 'rning'])],
      dtype=object)

In [ ]:
np.char.count(y,"a")

array([2, 2])

In [ ]:
np.char.startswith(y, "d")

array([False, False])

In [ ]:
np.char.replace(y,'a','xxxx')

array(['Dxxxxtxxxx Science', 'Mxxxxchine Lexxxxrning'], dtype='<U22')

In [ ]:
np.char.rjust(y,20,fillchar="*")

array(['********Data Science', '****Machine Learning'], dtype='<U20')

In [ ]:
np.char.ljust(y,20,fillchar="*")

array(['Data Science********', 'Machine Learning****'], dtype='<U20')

In [ ]:
# exponential function

import numpy as np

a = np.array([1, 2, 3, 4, 5])

exp_a = np.exp(a)

print("Original array:", a)
print("Exponential of the array:", exp_a)

Original array: [1 2 3 4 5]
Exponential of the array: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [ ]:

import numpy as np

b = np.array([[1, 2, 3], [4, 5, 6]])

exp_b = np.exp(b)

print("Original 2D array:\n", b)
print("Exponential of the 2D array:\n", exp_b)

Original 2D array:
 [[1 2 3]
 [4 5 6]]
Exponential of the 2D array:
 [[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [ ]:
#sqare roots finding

import numpy as np
a = np.array([1, 4, 7, 26, 15,7])

sqrt_a = np.sqrt(a)

print("Original array:", a)
print("Square root of the array:", sqrt_a)

Original array: [ 1  4  7 26 15  7]
Square root of the array: [1.         2.         2.64575131 5.09901951 3.87298335 2.64575131]


In [ ]:
#expo, sqrt,sin,cos,log

a=np.array([2,4,6])

print("sqrt of a:", np.sqrt(a))
print("exp of a:", np.exp(a))
print("sin of a:", np.sin(a))
print("cos of a:", np.cos(a))
print("log of a:", np.log(a))

sqrt of a: [1.41421356 2.         2.44948974]
exp of a: [  7.3890561   54.59815003 403.42879349]
sin of a: [ 0.90929743 -0.7568025  -0.2794155 ]
cos of a: [-0.41614684 -0.65364362  0.96017029]
log of a: [0.69314718 1.38629436 1.79175947]


In [ ]:
# aggregate function

a=np.array([1,2,4,5,6,7,8,9])
print("Sum:",np.sum(a))
print("Minimum Value:", np.min(a))
print("Mean Value:", np.mean(a))
print("Median Value:", np.median(a))
print("Corelation Coefficient:", np.corrcoef(a))
print("Standard Deviation:", np.std(a))



Sum: 42
Minimum Value: 1
Mean Value: 5.25
Median Value: 5.5
Corelation Coefficient: 1.0
Standard Deviation: 2.6339134382131846


In [ ]:
# assignment 1
--1
myList = [10, 20, 30, 'apple', True, 8.10]

# a. Append values 30 and 40
myList.append(30)
myList.append(40)

# b. Reverse the elements and store in 'reversedList'
reversedList = myList[::-1]

print("myList:", myList)
print("reversedList:", reversedList)

myList: [10, 20, 30, 'apple', True, 8.1, 30, 40]
reversedList: [40, 30, 8.1, True, 'apple', 30, 20, 10]


In [ ]:
# --2
myDict = {
    1: 'data',
    2: 'information',
    3: 'text'
}

# a. Eliminate the 'text' value from the dictionary
myDict = {k: v for k, v in myDict.items() if v != 'text'}

# b. Add 'features' to the dictionary
myDict[4] = 'features'

# c. Fetch the 'data' element from the dictionary and display it
for key, value in myDict.items():
    if value == 'data':
        print("Fetched element:", value)
        break

Fetched element: data


In [ ]:
#--3

my_tuple = (1, 2, 3, 'apple', 'mango')
print(my_tuple)

(1, 2, 3, 'apple', 'mango')


In [ ]:
#--4
numeric_tuple = (10, 20, 30, 40, 50)

# a. Find the minimum value
min_value = min(numeric_tuple)
print("Minimum value:", min_value)

# b. Concatenate my_tuple with numeric_tuple
r1 = my_tuple + numeric_tuple
print("Concatenated tuple (r1):", r1)

# c. Duplicate my_tuple 2 times
newdupli = my_tuple * 2
print("newdupli:", newdupli)

Minimum value: 10
Concatenated tuple (r1): (1, 2, 3, 'apple', 'mango', 10, 20, 30, 40, 50)
newdupli: (1, 2, 3, 'apple', 'mango', 1, 2, 3, 'apple', 'mango')


In [ ]:
#--5

set1 = {1, 2, 3, 4, 5}
set2 = {2, 3, 7, 6, 1}

# a. Union of set1 and set2
union = set1.union(set2)
print("Union:", union)

# b. Intersection of set1 and set2
intersection = set1.intersection(set2)
print("Intersection:", intersection)

# c. Difference of set1 from set2
difference = set1.difference(set2)
print("Difference:", difference)

Union: {1, 2, 3, 4, 5, 6, 7}
Intersection: {1, 2, 3}
Difference: {4, 5}


In [ ]:
# assignment 2
#--1

import numpy as np
matrix = np.arange(2, 11).reshape(3, 3)
print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
#--2
import numpy as np

user_input = input("Enter integers separated by spaces: ")
int_list = list(map(int, user_input.split()))

# Create a NumPy array from the integer list
int_array = np.array(int_list)

# Convert the array to float type
float_array = int_array.astype(float)

print("Original array:", int_array)
print("Array converted to float type:", float_array)

Enter integers separated by spaces: 1 2 3 4
Original array: [1 2 3 4]
Array converted to float type: [1. 2. 3. 4.]


In [ ]:
#--3
import numpy as np
array = np.array([10, 20, 30])
print("Original array:", array)

# Values to append
values_to_append = np.array([40, 50, 60, 70, 80, 90])

# Append values to the original array
updated_array = np.append(array, values_to_append)

# Display the result
print("Updated array after appending:", updated_array)

Original array: [10 20 30]
Updated array after appending: [10 20 30 40 50 60 70 80 90]


In [ ]:
import numpy as np
array1 = np.array([11, 22, 33])
array2 = np.array([44,55, 66])

# Add the arrays element-wise
sumArray = array1 + array2

print("Array 1:", array1)
print("Array 2:", array2)
print("Sum Array:", sumArray)

Array 1: [11 22 33]
Array 2: [44 55 66]
Sum Array: [55 77 99]


In [ ]:
#--5

import numpy as np
array1 = np.arange(10, 100, 10).reshape(3, 3)
print(array1)

# a. Extract the 1st row from the array
first_row = array1[0]
print("\nFirst row:", first_row)

# b. Extract the last element from the array
last_element = array1[2, 2]
print("\nLast element:", last_element)

[[10 20 30]
 [40 50 60]
 [70 80 90]]

First row: [10 20 30]

Last element: 90
